<?php
/**
 * One-time hosting installer for shared hosting (e.g. 076790.unisza.work).
 * Delete this file after setup, or leave it — it is locked via storage/hosting.lock.
 */
declare(strict_types=1);

$basePath = __DIR__;
$lockFile = $basePath . '/storage/hosting.lock';
$envFile = $basePath . '/.env';

$sqlCandidates = [
    $basePath . '/eye_system_hosting.sql',
    $basePath . '/deploy/eye_system_hosting.sql',
];
$sqlFile = null;
foreach ($sqlCandidates as $candidate) {
    if (is_file($candidate)) {
        $sqlFile = $candidate;
        break;
    }
}

if (is_file($lockFile)) {
    header('Location: index.php');
    exit;
}

$error = '';
$success = '';
$step = 'form';
$testOnly = false;

function h(string $value): string
{
    return htmlspecialchars($value, ENT_QUOTES, 'UTF-8');
}

function detect_app_url(): string
{
    $scheme = (!empty($_SERVER['HTTPS']) && $_SERVER['HTTPS'] !== 'off') ? 'https' : 'http';
    $host = $_SERVER['HTTP_HOST'] ?? 'localhost';
    $script = $_SERVER['SCRIPT_NAME'] ?? '/hosting_setup.php';
    $dir = str_replace('\\', '/', dirname($script));
    $dir = rtrim($dir, '/');
    if ($dir === '' || $dir === '.') {
        return $scheme . '://' . $host;
    }
    return $scheme . '://' . $host . $dir;
}

function write_env_file(string $path, array $values): bool
{
    $lines = [
        '# OphthaMind — production (.env generated by hosting_setup.php)',
        'APP_NAME=OphthaMind AI',
        'APP_ENV=production',
        'APP_DEBUG=false',
        'APP_URL=' . ($values['app_url'] ?? ''),
        '',
        'DB_HOST=' . ($values['db_host'] ?? 'localhost'),
        'DB_PORT=' . ($values['db_port'] ?? '3306'),
        'DB_NAME=' . ($values['db_name'] ?? ''),
        'DB_USER=' . ($values['db_user'] ?? ''),
        'DB_PASS=' . ($values['db_pass'] ?? ''),
        '',
        'SESSION_TIMEOUT=3600',
        'SESSION_NAME=eye_system_session',
        '',
        'UPLOAD_DIR=upload/',
        'MAX_UPLOAD_SIZE=5242880',
        'ALLOWED_TYPES=jpg,jpeg,png',
        '',
        'ENABLE_AI=false',
        'ENABLE_REGISTRATION=false',
        '',
    ];

    return file_put_contents($path, implode(PHP_EOL, $lines)) !== false;
}

function test_db(array $values): PDO
{
    $host = $values['db_host'] ?? 'localhost';
    $port = $values['db_port'] ?? '3306';
    $name = $values['db_name'] ?? '';
    $user = $values['db_user'] ?? '';
    $pass = $values['db_pass'] ?? '';

    if ($name === '' || $user === '') {
        throw new RuntimeException('Database name and user are required.');
    }

    $dsn = "mysql:host={$host};port={$port};dbname={$name};charset=utf8mb4";
    return new PDO($dsn, $user, $pass, [
        PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
    ]);
}

function import_sql_file(PDO $pdo, string $sqlPath): void
{
    if (!is_file($sqlPath)) {
        throw new RuntimeException('SQL file not found.');
    }

    $sql = file_get_contents($sqlPath);
    if ($sql === false || trim($sql) === '') {
        throw new RuntimeException('SQL file is empty.');
    }

    $pdo->exec('SET FOREIGN_KEY_CHECKS=0');
    $pdo->exec('SET NAMES utf8mb4');

    $buffer = '';
    $lines = preg_split('/\R/', $sql) ?: [];
    foreach ($lines as $line) {
        $trim = trim($line);
        if ($trim === '' || str_starts_with($trim, '--') || str_starts_with($trim, '/*')) {
            continue;
        }
        $buffer .= $line . "\n";
        if (substr(rtrim($line), -1) === ';') {
            $pdo->exec($buffer);
            $buffer = '';
        }
    }

    if (trim($buffer) !== '') {
        $pdo->exec($buffer);
    }

    $pdo->exec('SET FOREIGN_KEY_CHECKS=1');
}

$defaults = [
    'app_url' => detect_app_url(),
    'db_host' => 'localhost',
    'db_port' => '3306',
    'db_name' => '',
    'db_user' => '',
    'db_pass' => '',
    'import_sql' => $sqlFile ? '1' : '0',
];

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    $values = [
        'app_url' => trim((string) ($_POST['app_url'] ?? $defaults['app_url'])),
        'db_host' => trim((string) ($_POST['db_host'] ?? 'localhost')),
        'db_port' => trim((string) ($_POST['db_port'] ?? '3306')),
        'db_name' => trim((string) ($_POST['db_name'] ?? '')),
        'db_user' => trim((string) ($_POST['db_user'] ?? '')),
        'db_pass' => (string) ($_POST['db_pass'] ?? ''),
        'import_sql' => isset($_POST['import_sql']) ? '1' : '0',
    ];
    $testOnly = isset($_POST['test_only']);

    try {
        $pdo = test_db($values);

        if ($testOnly) {
            $tableCheck = $pdo->query("SHOW TABLES LIKE 'users'")->fetchColumn();
            if ($tableCheck) {
                $success = 'Connection OK — users table found. Click "Save & finish setup" below.';
            } elseif ($sqlFile) {
                $success = 'Connection OK — database is empty. Tick "Import database" then click "Save & finish setup".';
            } else {
                $success = 'Connection OK — but users table is missing. Import eye_system_hosting.sql in phpMyAdmin first.';
            }
            $defaults = array_merge($defaults, $values);
        } else {
            if (!write_env_file($envFile, $values)) {
                throw new RuntimeException('Could not write .env file. Check folder permissions.');
            }

            if ($values['import_sql'] === '1' && $sqlFile) {
                import_sql_file($pdo, $sqlFile);
                $success = 'Database imported and configuration saved.';
            } else {
                $tableCheck = $pdo->query("SHOW TABLES LIKE 'users'")->fetchColumn();
                if (!$tableCheck) {
                    throw new RuntimeException('Table "users" not found. Import eye_system_hosting.sql in phpMyAdmin, or tick "Import database".');
                }
                $success = 'Configuration saved. Existing database detected.';
            }

            if (!is_dir($basePath . '/storage')) {
                @mkdir($basePath . '/storage', 0755, true);
            }
            if (!is_dir($basePath . '/storage/logs')) {
                @mkdir($basePath . '/storage/logs', 0755, true);
            }
            if (!is_dir($basePath . '/upload')) {
                @mkdir($basePath . '/upload', 0755, true);
            }

            file_put_contents($lockFile, date('c') . PHP_EOL);
            $step = 'done';
        }
    } catch (Throwable $e) {
        $error = $e->getMessage();
        $defaults = array_merge($defaults, $values);
    }
}

$siteUrl = h($defaults['app_url']);
$hasSql = $sqlFile !== null;
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>OphthaMind Hosting Setup</title>
    <style>
        * { box-sizing: border-box; }
        body { font-family: system-ui, sans-serif; background: #eef2f7; margin: 0; padding: 20px; color: #0f172a; line-height: 1.55; }
        .wrap { max-width: 640px; margin: 0 auto; }
        .card { background: #fff; border: 1px solid #dbe3ef; border-radius: 16px; padding: 24px; margin-bottom: 16px; box-shadow: 0 10px 30px rgba(15,23,42,.05); }
        h1 { margin: 0 0 6px; font-size: 1.4rem; }
        h2 { margin: 0 0 10px; font-size: 1rem; color: #1565c0; }
        p, li { color: #475569; }
        ol { padding-left: 1.25rem; }
        ol li { margin-bottom: 8px; }
        label { display: block; font-weight: 600; margin: 14px 0 6px; font-size: .875rem; }
        input[type=text], input[type=password] { width: 100%; padding: 11px 12px; border: 1px solid #cbd5e1; border-radius: 10px; font-size: 1rem; }
        .row { display: grid; grid-template-columns: 1fr 90px; gap: 10px; }
        .hint { font-size: .8rem; color: #64748b; margin-top: 4px; }
        .check { margin-top: 14px; font-size: .9rem; display: flex; gap: 8px; align-items: flex-start; }
        .btns { display: grid; gap: 10px; margin-top: 18px; }
        button { padding: 13px; border: 0; border-radius: 10px; font-weight: 700; font-size: .95rem; cursor: pointer; }
        .btn-primary { background: #1565c0; color: #fff; }
        .btn-secondary { background: #e2e8f0; color: #0f172a; }
        .err { background: #fef2f2; color: #b91c1c; padding: 12px 14px; border-radius: 10px; margin-bottom: 12px; border: 1px solid #fecaca; }
        .ok { background: #ecfdf5; color: #047857; padding: 12px 14px; border-radius: 10px; margin-bottom: 12px; border: 1px solid #a7f3d0; }
        .step-box { background: #f8fafc; border: 1px dashed #cbd5e1; border-radius: 12px; padding: 16px; margin-top: 8px; }
        code { background: #f1f5f9; padding: 2px 6px; border-radius: 4px; font-size: .85rem; }
        a { color: #1565c0; font-weight: 600; }
        .badge { display: inline-block; background: #dbeafe; color: #1d4ed8; font-size: .75rem; font-weight: 700; padding: 3px 8px; border-radius: 999px; margin-bottom: 8px; }
    </style>
</head>
<body>
<div class="wrap">
    <?php if ($step === 'done'): ?>
    <div class="card">
        <span class="badge">DONE</span>
        <h1>Setup complete</h1>
        <?php if ($success): ?><div class="ok"><?= h($success) ?></div><?php endif; ?>
        <p>Your site is ready. AI screening stays <strong>offline</strong> on shared hosting — use XAMPP locally for predictions.</p>
        <p><a href="index.php">Open OphthaMind →</a></p>
        <p class="hint">Demo login (if data was imported): <code>ameer@clinic.my</code> — password from your database export.</p>
    </div>
    <?php else: ?>
    <div class="card">
        <span class="badge">3 EASY STEPS</span>
        <h1>OphthaMind Hosting Setup</h1>
        <p>Domain: <strong><?= h($_SERVER['HTTP_HOST'] ?? '') ?></strong></p>

        <div class="step-box">
            <h2>Step 1 — Create a MySQL database (onceamonth panel)</h2>
            <ol>
                <li>Open <a href="https://onceamonth.work" target="_blank" rel="noopener">onceamonth.work</a> and log in</li>
                <li>Click <strong>My Hosting / Domain</strong> → select <strong>076790.unisza.work</strong></li>
                <li>Find the <strong>MySQL</strong> or <strong>Database</strong> menu</li>
                <li>Click <strong>Create database</strong> — e.g. name it <code>ophthamind</code></li>
                <li>Create a <strong>user + password</strong> with full access to that database</li>
                <li><strong>Copy</strong> the database name, username, and password into the form below</li>
            </ol>
        </div>
    </div>

    <div class="card">
        <h2>Step 2 — Enter database details</h2>
        <p>Site URL is filled in automatically — <strong>do not change it</strong> unless you moved the folder.</p>

        <?php if ($error): ?><div class="err"><?= h($error) ?></div><?php endif; ?>
        <?php if ($success): ?><div class="ok"><?= h($success) ?></div><?php endif; ?>

        <form method="post">
            <label for="app_url">Site URL (auto)</label>
            <input type="text" id="app_url" name="app_url" value="<?= $siteUrl ?>" readonly style="background:#f8fafc;">

            <label for="db_name">Database name</label>
            <input type="text" id="db_name" name="db_name" value="<?= h($defaults['db_name']) ?>" placeholder="e.g. user_ophthamind" required>
            <div class="hint">Copy exactly from the hosting panel (case-sensitive).</div>

            <div class="row">
                <div>
                    <label for="db_user">Database user</label>
                    <input type="text" id="db_user" name="db_user" value="<?= h($defaults['db_user']) ?>" placeholder="e.g. user_db" required>
                </div>
                <div>
                    <label for="db_port">Port</label>
                    <input type="text" id="db_port" name="db_port" value="<?= h($defaults['db_port']) ?>">
                </div>
            </div>

            <label for="db_host">Database host</label>
            <input type="text" id="db_host" name="db_host" value="<?= h($defaults['db_host']) ?>">
            <div class="hint">Usually <code>localhost</code> — leave as-is unless the panel says otherwise.</div>

            <label for="db_pass">Database password</label>
            <input type="password" id="db_pass" name="db_pass" value="<?= h($defaults['db_pass']) ?>" placeholder="password from hosting panel">

            <?php if ($hasSql): ?>
            <label class="check">
                <input type="checkbox" name="import_sql" value="1" <?= $defaults['import_sql'] === '1' ? 'checked' : '' ?>>
                <span>Import bundled database (<code>eye_system_hosting.sql</code> — users, patients, etc.)</span>
            </label>
            <?php else: ?>
            <div class="step-box" style="margin-top:14px;">
                <strong>Step 1b — Manual SQL import</strong>
                <p style="margin:8px 0 0;">In the hosting panel, open <strong>phpMyAdmin</strong> → select your database → <strong>Import</strong> tab → choose <code>eye_system_hosting.sql</code> from your laptop → <strong>Go</strong>.</p>
                <p style="margin:8px 0 0;">File on your laptop: <code>C:\xampp\htdocs\eye_system\deploy\eye_system_hosting.sql</code></p>
            </div>
            <?php endif; ?>

            <div class="btns">
                <button type="submit" name="test_only" value="1" class="btn-secondary">Test connection first</button>
                <button type="submit" class="btn-primary">Save &amp; finish setup</button>
            </div>
        </form>
    </div>

    <div class="card">
        <h2>Step 3 — After setup</h2>
        <p>Open <a href="<?= $siteUrl ?>/"><?= $siteUrl ?>/</a> — you should see the OphthaMind login page.</p>
        <p class="hint">Stuck? Click "Test connection" first. If you get "Access denied", double-check user/password from the panel.</p>
    </div>
    <?php endif; ?>
</div>
</body>
</html>
